import { getSession, useSession } from "next-auth/react"
import Head from 'next/head'
import Feed from "../components/Feed";
import Header from '../components/Header'
import Login from '../components/Login';
import Sidebar from "../components/Sidebar";
import Widget from "../components/Widget";
import { db } from "../firebase";

// desturcturing props and getting session
export default function Home({ session, posts }) {

  // if user is not logged in return login page
  if (!session) return <Login />

  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex">
        <Sidebar />
        <Feed posts={posts} />
        <Widget />
      </main>

    </div>
  )
}


// server side rendering
export async function getServerSideProps(context) {
  // get the user session
  const session = await getSession(context);
  // prefetching
  const posts = await db.collection("posts").orderBy("timestamp", "desc").get()

  const docs = posts.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null

  }));

  return {
    props: {
      session,
      posts: docs
    }
  }
};